changed pre-commit

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -46,7 +46,16 @@ EOF
 fi
 
 ./gradlew ktlintFormat
+if [ $? -ne 0 ]; then
+  echo "ktlintFormat task failed, aborting commit."
+  exit 1
+fi
+
 ./gradlew build
+if [ $? -ne 0 ]; then
+  echo "Build task failed, aborting commit."
+  exit 1
+fi
 
 # If there are whitespace errors, print the offending file names and fail.
 exec git diff-index --check --cached $against --
